name: Go Weather Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_KEY_WEATHER: ${{ secrets.KEY_WEATHER }}
        envkey_TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        envkey_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false
    - name: execute my script
      run: go run weatherBot.go -cityName=MexicoCity -request=WF
